# Generated by Django 5.1.6 on 2025-06-20 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0006_profile_role_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseannouncement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
